<?php
namespace Xin\Thrift\MonitorService;
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface BaiduIf {
  /**
   * @param string $bdUss
   * @param string $nickName
   * @return bool
   * @throws \Xin\Thrift\MonitorService\ThriftException
   */
  public function tiebaSign($bdUss, $nickName);
  /**
   * @param string $bdUss
   * @param string $nickName
   * @return \Xin\Thrift\MonitorService\BaiduTieba[]
   * @throws \Xin\Thrift\MonitorService\ThriftException
   */
  public function myTiebas($bdUss, $nickName);
  /**
   * @param string $bdUss
   * @param string $nickName
   * @param string $name
   * @return \Xin\Thrift\MonitorService\BaiduTieba
   * @throws \Xin\Thrift\MonitorService\ThriftException
   */
  public function tieba($bdUss, $nickName, $name);
  /**
   * @param string $nickName
   * @return \Xin\Thrift\MonitorService\BaiduTieba[]
   * @throws \Xin\Thrift\MonitorService\ThriftException
   */
  public function tiebaList($nickName);
}


